### ISSUE TITLE
Windows 應避免使用 Alt+D 快速鍵

### ISSUE THREAD

**Issue by doggy8088** [JiaHongL/Chat-GPT-Custom-Prompt-Extension#1]
我剛發現這個套件有個 Alt+D 可以切換 Dark mode，不過在 Windows 的 Chrome 這個快速鍵被用來快速將游標移至「網址列」，如果裝了這個擴充套件後，Alt+D 就不會跳到網址列了，這樣等於強迫使用者改變習慣，我建議改掉這個快速鍵，謝謝。

另外，切換 Dark mode 的需求我認為沒有很大，一般人不會頻繁切換，所以設定快速鍵也比較沒有實質意義，若要移除這個快速鍵，我也是贊成的，供您參考！

**Comment by JiaHongL** [comment]
目前已經將 Alt + D 快捷鍵功能移除，系統送審約 2 ~ 4天，這邊就先把 issue 關閉了，感謝您的回饋！

由於收到多位使用者反映，我們的快捷鍵功能與其他插件或系統快捷鍵存在衝突，因此決定移除大多數的快捷鍵功能，僅保留那些具有輔助作用的快捷鍵。

**now**
- mainKey + Z : display or close shortcut tips
- esc : close dialog
- mainKey + S  : save
- mainKey + A : show / hidden right menu
- mainKey + B  : dark mode toggle
- mainKey + 1 ~ 5 number keyboard : open question dialog

**remove**
- mainKey + Y : custom quick reply
- mainKey + U : custom quick reply 2
- mainKey + I : custom quick reply 3
- mainKey + O : custom quick reply 4
- mainKey + P : custom quick 5
- mainKey + N： new chat
- mainKey + W : open settingsDialog
- mainKey + S : open settingsDialog
- mainKey + E : open quickReplySettingsDialog
- mainKey + F : open exportAndImportDialog
- mainKey + 6 ~ 0 number keyboard : open question dialog
- mainKey + R : regenerate response
- mainKey + X : stop
- mainKey + D : dark mode toggle

**modify**
- mainKey + B : dark mode toggle
