### ISSUE TITLE
保存的prompt是存储在哪里的？

### ISSUE THREAD

**Issue by ggbondpx** [JiaHongL/Chat-GPT-Custom-Prompt-Extension#3]
作者您好，我之前用这个插件写了很多定制化的prompt，但是由于GPT改版了，导出prompt的功能点击无反应，想去安装目录手动提取导出，谢谢~

**Comment by JiaHongL** [comment]
儲存在 web 的 localstorage 和 chrome.storage.local，若是清除過 localstorage 和 移除過 extension，就可能會把資料清掉，另外測試匯出匯入是正常的。
